##############################################################################
##############################################################################
#
# NOTE!
#
# Please read the README.md file in this directory that defines what should 
# be placed in this file
#
##############################################################################
##############################################################################

name: Checking workflow files
on:
  pull_request:
    paths:
      - '.github/**'
      - 'CNAME'
      - 'static/CNAME'
      - 'package.json'
      - 'sidebars.js'
      - 'sidebar-admin.js'
      - 'sidebar-mobile-user.js'
      - 'sidebar-web-user.js'
      - 'docusaurus.config.js'
      - 'babel.config.js'
      - 'CODEOWNERS'
      - 'LICENSE'

jobs:
  Checking-for-unauthorized-file-changes:
    name: Checking for unauthorized file changes
    runs-on: ubuntu-latest

    steps:
      - name: Unauthorized file modification in PR
        run: exit 1
